#!/usr/bin/python3
import intcodeComputer
import sys
from itertools import permutations

if __name__ == "__main__":
    with open(sys.argv[-1]) as f:
        code = f.read().split(',')
        max_out = 0
        for phases in permutations([5, 6, 7, 8, 9]):
            amp_a = intcodeComputer.IntcodeComputer(code)
            amp_b = intcodeComputer.IntcodeComputer(code)
            amp_c = intcodeComputer.IntcodeComputer(code)
            amp_d = intcodeComputer.IntcodeComputer(code)
            amp_e = intcodeComputer.IntcodeComputer(code)
            ret = 0
            last_out = None
            while( not (amp_a.halted() and amp_b.halted() and amp_c.halted() and amp_d.halted() and amp_e.halted())):
                ret = amp_a.run([phases[0], ret])
                ret = amp_b.run([phases[1], ret])
                ret = amp_c.run([phases[2], ret])
                ret = amp_d.run([phases[3], ret])
                ret = amp_e.run([phases[4], ret])
                if (ret != None):
                    last_out = ret
            if last_out > max_out:
                max_out = last_out
        print(max_out)
